### ISSUE TITLE
[INFRA] [FT21-0] Create CloudFormation template for dex-roles stack

### ISSUE THREAD

**Issue by MatheusMiranda** [dexlabsio/terraform-modules#3]
## Description
Currently, our customers configure their Athena/Glue/roles resources using a [public terraform module](https://github.com/dexlabsio/terraform-modules/tree/main/aws/terraform/dex-roles) shared by us.

To use this Terraform, the customers need to configure a whole terraform setup on their side; This is not a good experience for the customers and slows down the whole setup process.

## Proposed Solution
To improve this process, we must create an analog CloudFormation stack, this way the customers can deploy the resources directly on AWS panel.

## Additional comment
In addition to publishing the CloudFormation stack on our terraform-modules repository, we must publish the template in our public bucket, so we can reference the template directly during the user setup process.

## Tasks
- [x] Create a CloudFormation stack version of our dex-roles terraform module;
- [x] Publish the template in both terraform-modules repository and in our public-assets bucket;
- [x] Setup CI on terraform-modules to automatically update the stack template in the bucket dex-public-assets;

**Comment by MatheusMiranda** [comment]
This is the url pattern we should redirect our users for, during the setup process:
https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create?templateURL=https://dex-public-assets.s3.us-east-1.amazonaws.com/cloudformation/dex_roles.yaml
